# 站点配置
title:       Mystery Review
SEOTitle:    Mystery Review 诚实点评推理本
header-img:  ""
description: 开源、非商业、力求言之有物的推理本测评
keyword:     剧本杀, 剧本杀测评, 推理, 还原, 刑侦, 解谜
RSS:         true
url:         https://mysteryreview.github.io
github_repo: https://github.com/mysteryreview/mysteryreview.github.io.git
github_username: mysteryreview

# 页面配置
permalink: pretty             # 详见: http://jekyllcn.com/docs/permalinks/
paginate:  20                 # 单页文章数
exclude:   ["README.md"]

# 文本配置
markdown: kramdown            # 详见: http://jekyllrb.com/docs/configuration/#kramdown
highlighter: rouge
kramdown:
  input: GFM 
